### ISSUE TITLE
UI updates not occurring

### ISSUE THREAD

**Issue by dethell** [beije/AsyncIterator#1]
First, thanks for a great way to process large datasets in the background!

I am using AsyncIterator to process a large array of javascript objects for charting purposes. During the process I am updating a bootstrap progress bar. No matter what the batch size is I never see any UI updates until the loop is complete and then all the UI updates happen at once.

Even if I remove the progress bar dependency and just update an html element with the current percentage it waits until the end to update. All the data is processing correctly and the rest of our UI is responsive to user interaction so I know the task is properly in the "background".

I can't really reproduce the entire code here as the worker function is rather large. Is there something I should look for in the worker that might be holding up the UI until completion of the entire loop?

**Comment by beije** [comment]
@dethell can you create a codepen or something which shows the problem (like with the minimum amount of code)?
